# Generated by Django 3.0 on 2021-04-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eb_tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='answers_false',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1, verbose_name='неправильный ответ'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='answers_true',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1, verbose_name='правильный ответ'),
        ),
    ]
